### ISSUE TITLE
403 Forbidden - access to WebGUI denied

### ISSUE THREAD

**Issue by 7wells** [dfigus/addon-tvheadend#151]
## The Problem

AFter deinstalling the other tvheadend addon and installing this one, I run through the initialisation in the WebGUI, finally entering admin name + password and normal username + password. I read that the admin account would be disabled and wanted to proceed.

By the way, why is the tvheadend addon admin account to be disabled?

Well, I thought that's ok, since I had just entered also a normal username + password. However, when I opened the WebGUI and entered my normal username + password, I got "403 Forbidden".

Even after deinstalling and reinstalling this addon, I can no longer access the WebGUI. I have ssh access to `addon_configs/dae55a80_tvheadend/tvheadend/accesscontrol`, where I see two files, one for the admin user, the other for the normal user. Both contain 'enabled: true', so I don't know what the problem is.

How can I solve this problem? Thanks a lot for your help, Daniel!

## Environment

- Addon version: 5.1.4
- HA OS version: 2024.3.0
- Installation methode: HA OS 12.1
- Hardware: RPI 4

## Logs

NA

## Steps to reproduce

See above

## Additional Information

NA

**Comment by dfigus** [comment]
The `accesscontrol` folder contains the access entries you created from the TVH webui Configuration->Users. If you delete the complete config folder of TVH it will create a new initial configuration which will allow admin access for non-logged-in users. Please note that my new addon stores the config folder in a different location (`addon_configs`) as the old way of storing this inside the homeassistant config folder as subfolder is deprecated. Hence you cannot simply switch between different addons easily. Also my addon runs the current TVH version built from the latest 4.3 dev branch which is slightly incompatible with the TVH 4.2 from the other addon.

Hence my personal advice: Don't switch between addons, nor install them over each other. You will most probably break something and end up in a weird state with unpredictable results.
