### ISSUE TITLE
Unable to add locale URL file

### ISSUE THREAD

**Issue by Facy5** [dfigus/addon-tvheadend#159]
## The Problem

It seems TVH isn't able to see any folders/files if I want to add an `.m3u` playlist stored localy inside TVH folders with the ``file:///`` protocol. But I can clearly see it with FileBrowser.

I also tried store it some others folders (inside _and_ outside TVH addon folder, like media, usr, or even the root folder)

Have I missed something ?

## Environment

- Addon version: 5.1.5
- HA Core : 2024.3.3
- HA Supervisor: 2024.03.1
- HA OS: 12.1
- Installation method: HA OS/Supervised on Proxmox Virtual Environment 8.1.4
- Hardware: generic x86_64

## Logs

```[txt]
iptv: unable to open file '/tvheadend/YourPlaylist.m3u': No such file or directory
```

## Steps to reproduce
With FileBrowser, add an .m3u in addon_configs\[AutoGeneratedNumber]_tvheadend\tvheadend\

In TVH :
Go to Configuration > DVB Input > Network > Add
URL : file:///tvheadend/YourPlaylist.m3u
Save

**Comment by dfigus** [comment]
Hi @Facy5,

welcome to the addon 😁. In my opinion the URL you use is incorrect. Inside the addon, the path would be `/config/tvheadend`, hence your URL should be

```
file:///config/tvheadend/YourPlaylist.m3u
```

You could also drop m3u this into the HA share or media folder which are mapped to `/share` and `/media` inside the addon.

**Comment by Facy5** [comment]
Yes, it was that !
But, why TVH see with `/config` and not directly `/tvheadend` (just for my knowledge) ?

> You could also drop m3u this into the HA share or media folder which are mapped to `/share` and `/media `inside the addon.

Yes, I didn't think about them
