### ISSUE TITLE
v5.1.7 fails with "[error] 201#201: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2"

### ISSUE THREAD

**Issue by 7wells** [dfigus/addon-tvheadend#175]
Sorry, Daniel, please delete this "issue", as it was resolved after 2 HA restarts. :)

**Comment by dfigus** [comment]
Hi @7wells,

see also #174 - those are errors which should not impact the functionality. However #176 should avoid those errors. I'll create a release as soon as the build is complete.

**Comment by dfigus** [comment]
Closing this one as a duplicate of #174
