### ISSUE TITLE
Error relocating /usr/bin/tvheadend since 5.1.12

### ISSUE THREAD

**Issue by n4vm4n-0ne** [dfigus/addon-tvheadend#225]
## The Problem

After update to 5.1.12, addon is unable to start

## Environment

- Addon version: 5.1.12
- HA OS version: 2024.7.3
- Installation methode: Supervised
- Hardware: RPI  4, supervised

## Logs

Error relocating /usr/bin/tvheadend: av_packet_unref: symbol not found
Error relocating /usr/bin/tvheadend: av_log_set_callback: symbol not found
Error relocating /usr/bin/tvheadend: av_get_sample_fmt_name: symbol not found
Error relocating /usr/bin/tvheadend: av_read_frame: symbol not found
Error relocating /usr/bin/tvheadend: av_dict_get_string: symbol not found
Error relocating /usr/bin/tvheadend: av_default_item_name: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_open2: symbol not found
Error relocating /usr/bin/tvheadend: av_buffersrc_parameters_set: symbol not found
Error relocating /usr/bin/tvheadend: av_packet_from_data: symbol not found
Error relocating /usr/bin/tvheadend: av_buffer_unref: symbol not found
Error relocating /usr/bin/tvheadend: avfilter_graph_free: symbol not found
Error relocating /usr/bin/tvheadend: av_interleaved_write_frame: symbol not found
Error relocating /usr/bin/tvheadend: avfilter_get_by_name: symbol not found
Error relocating /usr/bin/tvheadend: avformat_find_stream_info: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_parameters_copy: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_find_decoder: symbol not found
Error relocating /usr/bin/tvheadend: avfilter_graph_set_auto_convert: symbol not found
Error relocating /usr/bin/tvheadend: avfilter_graph_parse_ptr: symbol not found
Error relocating /usr/bin/tvheadend: av_get_channel_layout_string: symbol not found
Error relocating /usr/bin/tvheadend: av_hwframe_ctx_init: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_receive_frame: symbol not found
Error relocating /usr/bin/tvheadend: av_buffersink_get_frame_flags: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_free_context: symbol not found
Error relocating /usr/bin/tvheadend: av_malloc: symbol not found
Error relocating /usr/bin/tvheadend: av_buffer_ref: symbol not found
Error relocating /usr/bin/tvheadend: av_hwframe_get_buffer: symbol not found
Error relocating /usr/bin/tvheadend: av_rescale_q_rnd: symbol not found
Error relocating /usr/bin/tvheadend: av_get_pix_fmt_name: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_get_hw_config: symbol not found
Error relocating /usr/bin/tvheadend: av_dict_get: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_find_encoder: symbol not found
Error relocating /usr/bin/tvheadend: av_frame_unref: symbol not found
Error relocating /usr/bin/tvheadend: av_frame_free: symbol not found
Error relocating /usr/bin/tvheadend: avfilter_graph_alloc: symbol not found
Error relocating /usr/bin/tvheadend: av_rescale_q: symbol not found
Error relocating /usr/bin/tvheadend: av_frame_alloc: symbol not found
Error relocating /usr/bin/tvheadend: avfilter_graph_dump: symbol not found
Error relocating /usr/bin/tvheadend: av_hwdevice_ctx_create: symbol not found
Error relocating /usr/bin/tvheadend: av_get_channel_layout_nb_channels: symbol not found
Error relocating /usr/bin/tvheadend: avio_open: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_parameters_from_context: symbol not found
Error relocating /usr/bin/tvheadend: avfilter_graph_config: symbol not found
Error relocating /usr/bin/tvheadend: av_dict_set: symbol not found
Error relocating /usr/bin/tvheadend: avformat_alloc_output_context2: symbol not found
Error relocating /usr/bin/tvheadend: av_dict_set_int: symbol not found
Error relocating /usr/bin/tvheadend: avformat_write_header: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_send_frame: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_default_get_buffer2: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_find_encoder_by_name: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_is_open: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_receive_packet: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_send_packet: symbol not found
Error relocating /usr/bin/tvheadend: av_bsf_alloc: symbol not found
Error relocating /usr/bin/tvheadend: av_buffersink_set_frame_size: symbol not found
Error relocating /usr/bin/tvheadend: avformat_close_input: symbol not found
Error relocating /usr/bin/tvheadend: avformat_network_deinit: symbol not found
Error relocating /usr/bin/tvheadend: av_get_media_type_string: symbol not found
Error relocating /usr/bin/tvheadend: avformat_new_stream: symbol not found
Error relocating /usr/bin/tvheadend: av_strerror: symbol not found
Error relocating /usr/bin/tvheadend: av_bsf_send_packet: symbol not found
Error relocating /usr/bin/tvheadend: avformat_network_init: symbol not found
Error relocating /usr/bin/tvheadend: av_hwdevice_hwconfig_alloc: symbol not found
Error relocating /usr/bin/tvheadend: av_freep: symbol not found
Error relocating /usr/bin/tvheadend: av_buffersrc_add_frame_flags: symbol not found
Error relocating /usr/bin/tvheadend: av_bsf_init: symbol not found
Error relocating /usr/bin/tvheadend: avformat_alloc_context: symbol not found
Error relocating /usr/bin/tvheadend: av_dict_free: symbol not found
Error relocating /usr/bin/tvheadend: avfilter_inout_free: symbol not found
Error relocating /usr/bin/tvheadend: avio_closep: symbol not found
Error relocating /usr/bin/tvheadend: av_bsf_get_by_name: symbol not found
Error relocating /usr/bin/tvheadend: av_hwdevice_get_hwframe_constraints: symbol not found
Error relocating /usr/bin/tvheadend: avfilter_inout_alloc: symbol not found
Error relocating /usr/bin/tvheadend: av_mallocz: symbol not found
Error relocating /usr/bin/tvheadend: av_mul_q: symbol not found
Error relocating /usr/bin/tvheadend: avcodec_alloc_context3: symbol not found
Error relocating /usr/bin/tvheadend: av_write_trailer: symbol not found
Error relocating /usr/bin/tvheadend: av_bsf_free: symbol not found
Error relocating /usr/bin/tvheadend: av_buffersrc_parameters_alloc: symbol not found
[11:59:54] INFO: Service tvheadend exited with code 127 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service init-comskip: stopping
s6-rc: info: service nginx: stopping
s6-rc: info: service init-comskip successfully stopped
s6-rc: info: service nginx successfully stopped
s6-rc: info: service tvheadend: stopping
s6-rc: info: service tvheadend successfully stopped
s6-rc: info: service init-tvheadend: stopping
s6-rc: info: service init-tvheadend successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

## Steps to reproduce

Start the addon from HA

## Additional Information

Was working fine before the update.

**Comment by dfigus** [comment]
Thanks for reporting! I think I know what the root cause is and will report back soon.

**Comment by dfigus** [comment]
@n4vm4n-0ne Can you give 5.1.13 a try? This should fix the issue. 

Sorry for breaking it, I somehow mixed ffmpeg4 and ffmpeg6.

**Comment by n4vm4n-0ne** [comment]
thanks @dfigus. All working fine now.

Also, just wanted to thank you for the awesome work you have done with this addon. I have had a basic setup before, and your version is so much more awesome and fun :)
