### ISSUE TITLE
error 500 when making changes in tvheadend (browser issue leads to general freeze of addons in HA)

### ISSUE THREAD

**Issue by rucati** [dfigus/addon-tvheadend#46]
# Problem/Motivation

Tvheadend freezes as soon as you start configuring
Extra: addon was installed on latest HAOS and debian + superviserd
All tested dvb cards are on satip server (minisatip + fritzbox 6490).

> (Why the issue was filed
This is a browser issue caused by this addon. Disabling this addon turns HA into a hassle free system.

## Expected behavior

Being able to config tvheadend from within HAOS using satip-tuners (host network required)
 
> (What you expected to happen)

## Actual behavior

After installing the addon, tvheadend runs fine. No errors in the log. 
But configuring tvheadend leads to a freeze after changing some items. 
I.e. sorting services based on FTA or encrypted doesn't list the channels in the expected column. 
Then moving to other items in tvheadend results in an empty page (although the menu structure of tvheadend remains responsive and accessible + still no errors in the addon log).
After that every addon (including tvheadend) results in an error 500 (server got intself into trouble).
Still no errors in the log of the addon.

## Steps to reproduce
Configuring tvheadend in Firefox, Chrome or Edge on Windows or Linux result into this behaviour.

> (How can someone else make/see it happen)
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Clearing the cache/cookies of the browser make it work again (until you change something in tvheadend.

**Comment by dfigus** [comment]
Thanks for reporting, I also came across this. I even had this just with the ssh addon, without tvheadend installed (so this might be a general HA OS issue). The 500 error comes directly from HA OS and not from the addon. Did you configure tvheadend via the embedded UI?

Nevertheless I will try to reproduce it and analyze.

As a workaround you can directly access tvheadend via <homeassistantIp/Hostname>:9981 and configure it. I did it this way.

**Comment by dfigus** [comment]
@rucati I think I could reproduce the issue while sorting in the channel list. Can you check the supervisor logs on your end? I have the following error in there:
`http.cookies.CookieError: Illegal key 'ys-api/channel'` - so it could be a different cookie name here, but the `ys-` seems to come from TVheadend. When you sort a column in TVheadend, this cookie is set and afterwards the error occurs. Once the cookie is deleted, everything works fine.

**Comment by dfigus** [comment]
@rucati The root cause for this issue is that the tvheadend webui uses `/` as cookie name which is not working with python. Refer to tvheadend issue [6078](https://tvheadend.org/issues/6078) and python doc for [http.cookies](https://docs.python.org/3/library/http.cookies.html#module-http.cookies) which does not list `/` as the allowed character for the cookie name.

To workaround this I patched the ext js lib from the tvheadend to `URIComponent` encode the cookie name... Dirty, but this seems to work for the channel sorting from above. Can you check release v4.1.2?

**Comment by rucati** [comment]
Indeed, this works for me too. Great! I keep you updated

**Comment by dfigus** [comment]
Thanks for the feedback. Please reopen or create a new issue in case you encounter another 500 error.
